### ISSUE TITLE
Can't import FULL release file after deployment

### ISSUE THREAD

**Issue by rathpanyowat** [IHTSDO/snowstorm-deploy#3]
I have followed the README.md file and successfully deploy snowstorm to Ubuntu 20.04 LTS. However, when I tried to create an import job like this.

`{
  "branchPath": "MAIN",
  "createCodeSystemVersion": true,
  "type": "FULL"
}`

The server returned with

`{
  "error": "BAD_REQUEST",
  "message": "FULL import is only implemented for the MAIN branch and when there is no existing content."
}`

I haven't done anything to the server before.

I have tried to run the snowstorm.jar directly with `--import-full` but it doesn't work either with the same error message.

The SNAPSHOT import work without any problems. I'm not sure I did something wrong or it's the problem from the code side.

**Comment by kaicode** [comment]
Hi Rath. What version of Snowstorm are you using? Also what response do you get when you list concepts using `/MAIN/concepts` ?

**Comment by rathpanyowat** [comment]
Thanks for response @kaicode 

I followed this [README](https://github.com/IHTSDO/snowstorm-deploy/tree/main/ubuntu_20.04_LTS) page. I think snowstorm version is 9.2.0. Actually, I only run these two commands.

- Install Elasticsearch: [install_elasticsearch.sh](install_elasticsearch.sh)
- Install Snowstorm (including Java 17): [install_snowstorm.sh](install_snowstorm.sh)

About the response, this is what I got:

```
{
  "items": [
    
  ],
  "total": 0,
  "limit": 50,
  "offset": 0
}
```

**Comment by kaicode** [comment]
This is fixed in later versions of Snowstorm, (see [Snowstorm issue 575](https://github.com/IHTSDO/snowstorm/issues/575).
I will attempt to update these deployment scripts in the next few weeks to use the latest Snowstorm version.

**Comment by rathpanyowat** [comment]
I see. Thanks!

**Comment by kaicode** [comment]
@rathpanyowat I have now developed, tested and released the deployment scripts for the latest Snowstorm, version 10.2.1. 
To use the new versions just [follow the deployment steps](https://github.com/IHTSDO/snowstorm-deploy/tree/main/ubuntu_20.04_LTS) the same as before.

Elasticsearch, Snowstorm and Nginx deploy well on Ubuntu 20. 
The FULL import starts okay on this version. The full import is still running for me, it will take many hours so I will let it run overnight.

**Comment by kaicode** [comment]
The FULL (full history) import of 72 International releases just completed. 
Snowstorm was deployed using the latest deployment scripts, on an AWS EC2 instance type `t2.xlarge` (16g of RAM) using Ubuntu 20.04.
The import took just over 3 hours.
